name: Package and release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses:
          actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Package and release classic
        uses: BigWigsMods/packager@master
        with:
          args: -g 1.14.0
 